global:
  name: consul
  domain: consul
  datacenter: josh1
  image: hashicorp/consul-enterprise:1.9.0-ent-beta1
  imageEnvoy: "envoyproxy/envoy-alpine:v1.15.0"       # 1.15.0 Updates Intentions MUCH faster than 1.14.x

  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

  tls:
    enabled: true

  enableConsulNamespaces: true                        # CRDs won't setup Consul namespaces correctly if this is false (default)

  # federation:                               # No federation since this is a single cluster deployment.
  #   enabled: true
  #   createFederationSecret: true

  acls:
    manageSystemACLs: true
    createReplicationToken: true

server:
  replicas: 3
  bootstrapExpect: 3

client:
  enabled: true
  grpc: true

ui:
  enabled: true
  service:
    type: LoadBalancer

connectInject:
  enabled: true

syncCatalog:
  enabled: true
  k8sDenyNamespaces: ["kube-system", "kube-public"]

controller:       # Enabled CRDs
  enabled: true