apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: api
  namespace: default
spec:
  protocol: grpc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "cache:9092,payments:9093"
    spec:
      serviceAccountName: api
      containers:
      - name: api
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9091"
          - name: UPSTREAM_URIS
            value: "http://127.0.0.1:9092, http://127.0.0.1:9093"
          - name: MESSAGE
            value: "API response"
          - name: NAME
            value: "api"
          - name: SERVER_TYPE
            value: "grpc"
          - name: TIMING_50_PERCENTILE
            value: "20ms"
          - name: TIMING_90_PERCENTILE
            value: "30ms"
          - name: TIMING_90_PERCENTILE
            value: "40ms"
          - name: TIMING_VARIANCE
            value: "10"
          - name: TRACING_ZIPKIN
            value: "http://jaeger-collector-default.service.aks1.consul:9411"
