apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: currency-all
  namespace: default
spec:
  protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: currency-all
spec:
  routes:
    - match:
        http:
          pathPrefix: /v2
      destination:
        service: currency-v2
        namespace: default
    - match:
        http:
          pathPrefix: /
      destination:
        service: currency
        namespace: default