apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: payments
  namespace: default
spec:
  protocol: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "currency-all:9094"
    spec:
      serviceAccountName: payments
      containers:
      - name: payments
        image: "nicholasjackson/fake-service:v0.17.6"
        imagePullPolicy: Always
        ports:
        - containerPort: 9093
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9093"
          - name: UPSTREAM_URIS
            value: "http://127.0.0.1:9094/server2/api/command1, http://127.0.0.1:9094/api/command1"
          - name: MESSAGE
            value: "Payments response"
          - name: NAME
            value: "payments"
          - name: SERVER_TYPE
            value: "http"
          # - name: TRACING_ZIPKIN
          #   value: "http://jaeger-collector-default.service.aks1.consul:9411"
          - name:  HTTP_CLIENT_REQUEST_TIMEOUT
            value: "10s"
